// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boiler.proto

package grpc.Boiler;

public interface BoilerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoilerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSafe = 1;</code>
   */
  boolean getIsSafe();
}
