// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boiler.proto

package grpc.Boiler;

public final class BoilerImpl {
  private BoilerImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoilerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoilerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoilerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoilerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014boiler.proto\"&\n\rBoilerRequest\022\025\n\remiss" +
      "ionGases\030\001 \001(\t\" \n\016BoilerResponse\022\016\n\006isSa" +
      "fe\030\001 \001(\0102G\n\rBoilerService\0226\n\021sendBoilerR" +
      "equest\022\016.BoilerRequest\032\017.BoilerResponse(" +
      "\001B\033\n\013grpc.BoilerB\nBoilerImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BoilerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BoilerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoilerRequest_descriptor,
        new java.lang.String[] { "EmissionGases", });
    internal_static_BoilerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BoilerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoilerResponse_descriptor,
        new java.lang.String[] { "IsSafe", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
