// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: boiler.proto

package grpc.Boiler;

public interface BoilerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoilerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string emissionGases = 1;</code>
   */
  java.lang.String getEmissionGases();
  /**
   * <code>string emissionGases = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmissionGasesBytes();
}
