// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterQuality.proto

package grpc.waterQuality;

public interface SampleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SampleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sample_id = 1;</code>
   */
  java.lang.String getSampleId();
  /**
   * <code>string sample_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
