// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterQuality.proto

package grpc.waterQuality;

public final class WaterQualityImpl {
  private WaterQualityImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022waterQuality.proto\";\n\rSampleRequest\022\n\n" +
      "\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003 \001(" +
      "\t\"4\n\016SampleResponse\022\021\n\tsample_id\030\001 \001(\t\022\017" +
      "\n\007success\030\002 \001(\0102K\n\022waterSampleService\0225\n" +
      "\014CreateSample\022\016.SampleRequest\032\017.SampleRe" +
      "sponse\"\000(\0010\001B\'\n\021grpc.waterQualityB\020Water" +
      "QualityImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Location", });
    internal_static_SampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleResponse_descriptor,
        new java.lang.String[] { "SampleId", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
