// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicalWaste.proto

package grpc.poluttionMonitoring;

/**
 * Protobuf type {@code containsBagId}
 */
public  final class containsBagId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:containsBagId)
    containsBagIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use containsBagId.newBuilder() to construct.
  private containsBagId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private containsBagId() {
    tagRequest_ = "";
    tagResponse_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private containsBagId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            tagRequest_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tagResponse_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.poluttionMonitoring.MedicalWasteImpl.internal_static_containsBagId_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.poluttionMonitoring.MedicalWasteImpl.internal_static_containsBagId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.poluttionMonitoring.containsBagId.class, grpc.poluttionMonitoring.containsBagId.Builder.class);
  }

  public static final int TAGREQUEST_FIELD_NUMBER = 1;
  private volatile java.lang.Object tagRequest_;
  /**
   * <code>string tagRequest = 1;</code>
   */
  public java.lang.String getTagRequest() {
    java.lang.Object ref = tagRequest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tagRequest_ = s;
      return s;
    }
  }
  /**
   * <code>string tagRequest = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTagRequestBytes() {
    java.lang.Object ref = tagRequest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tagRequest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGRESPONSE_FIELD_NUMBER = 2;
  private volatile java.lang.Object tagResponse_;
  /**
   * <code>string tagResponse = 2;</code>
   */
  public java.lang.String getTagResponse() {
    java.lang.Object ref = tagResponse_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tagResponse_ = s;
      return s;
    }
  }
  /**
   * <code>string tagResponse = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTagResponseBytes() {
    java.lang.Object ref = tagResponse_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tagResponse_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTagRequestBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tagRequest_);
    }
    if (!getTagResponseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tagResponse_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTagRequestBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tagRequest_);
    }
    if (!getTagResponseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tagResponse_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.poluttionMonitoring.containsBagId)) {
      return super.equals(obj);
    }
    grpc.poluttionMonitoring.containsBagId other = (grpc.poluttionMonitoring.containsBagId) obj;

    boolean result = true;
    result = result && getTagRequest()
        .equals(other.getTagRequest());
    result = result && getTagResponse()
        .equals(other.getTagResponse());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TAGREQUEST_FIELD_NUMBER;
    hash = (53 * hash) + getTagRequest().hashCode();
    hash = (37 * hash) + TAGRESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + getTagResponse().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.poluttionMonitoring.containsBagId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.poluttionMonitoring.containsBagId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.poluttionMonitoring.containsBagId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.poluttionMonitoring.containsBagId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.poluttionMonitoring.containsBagId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.poluttionMonitoring.containsBagId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.poluttionMonitoring.containsBagId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.poluttionMonitoring.containsBagId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.poluttionMonitoring.containsBagId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.poluttionMonitoring.containsBagId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.poluttionMonitoring.containsBagId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.poluttionMonitoring.containsBagId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.poluttionMonitoring.containsBagId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code containsBagId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:containsBagId)
      grpc.poluttionMonitoring.containsBagIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.poluttionMonitoring.MedicalWasteImpl.internal_static_containsBagId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.poluttionMonitoring.MedicalWasteImpl.internal_static_containsBagId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.poluttionMonitoring.containsBagId.class, grpc.poluttionMonitoring.containsBagId.Builder.class);
    }

    // Construct using grpc.poluttionMonitoring.containsBagId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tagRequest_ = "";

      tagResponse_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.poluttionMonitoring.MedicalWasteImpl.internal_static_containsBagId_descriptor;
    }

    @java.lang.Override
    public grpc.poluttionMonitoring.containsBagId getDefaultInstanceForType() {
      return grpc.poluttionMonitoring.containsBagId.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.poluttionMonitoring.containsBagId build() {
      grpc.poluttionMonitoring.containsBagId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.poluttionMonitoring.containsBagId buildPartial() {
      grpc.poluttionMonitoring.containsBagId result = new grpc.poluttionMonitoring.containsBagId(this);
      result.tagRequest_ = tagRequest_;
      result.tagResponse_ = tagResponse_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.poluttionMonitoring.containsBagId) {
        return mergeFrom((grpc.poluttionMonitoring.containsBagId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.poluttionMonitoring.containsBagId other) {
      if (other == grpc.poluttionMonitoring.containsBagId.getDefaultInstance()) return this;
      if (!other.getTagRequest().isEmpty()) {
        tagRequest_ = other.tagRequest_;
        onChanged();
      }
      if (!other.getTagResponse().isEmpty()) {
        tagResponse_ = other.tagResponse_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.poluttionMonitoring.containsBagId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.poluttionMonitoring.containsBagId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object tagRequest_ = "";
    /**
     * <code>string tagRequest = 1;</code>
     */
    public java.lang.String getTagRequest() {
      java.lang.Object ref = tagRequest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tagRequest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tagRequest = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTagRequestBytes() {
      java.lang.Object ref = tagRequest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tagRequest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tagRequest = 1;</code>
     */
    public Builder setTagRequest(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tagRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tagRequest = 1;</code>
     */
    public Builder clearTagRequest() {
      
      tagRequest_ = getDefaultInstance().getTagRequest();
      onChanged();
      return this;
    }
    /**
     * <code>string tagRequest = 1;</code>
     */
    public Builder setTagRequestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tagRequest_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tagResponse_ = "";
    /**
     * <code>string tagResponse = 2;</code>
     */
    public java.lang.String getTagResponse() {
      java.lang.Object ref = tagResponse_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tagResponse_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tagResponse = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTagResponseBytes() {
      java.lang.Object ref = tagResponse_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tagResponse_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tagResponse = 2;</code>
     */
    public Builder setTagResponse(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tagResponse_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tagResponse = 2;</code>
     */
    public Builder clearTagResponse() {
      
      tagResponse_ = getDefaultInstance().getTagResponse();
      onChanged();
      return this;
    }
    /**
     * <code>string tagResponse = 2;</code>
     */
    public Builder setTagResponseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tagResponse_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:containsBagId)
  }

  // @@protoc_insertion_point(class_scope:containsBagId)
  private static final grpc.poluttionMonitoring.containsBagId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.poluttionMonitoring.containsBagId();
  }

  public static grpc.poluttionMonitoring.containsBagId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<containsBagId>
      PARSER = new com.google.protobuf.AbstractParser<containsBagId>() {
    @java.lang.Override
    public containsBagId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new containsBagId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<containsBagId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<containsBagId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.poluttionMonitoring.containsBagId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

