// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicalWaste.proto

package grpc.poluttionMonitoring;

public interface containsBagIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsBagId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tagRequest = 1;</code>
   */
  java.lang.String getTagRequest();
  /**
   * <code>string tagRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagRequestBytes();

  /**
   * <code>string tagResponse = 2;</code>
   */
  java.lang.String getTagResponse();
  /**
   * <code>string tagResponse = 2;</code>
   */
  com.google.protobuf.ByteString
      getTagResponseBytes();
}
