// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medicalWaste.proto

package grpc.poluttionMonitoring;

public final class MedicalWasteImpl {
  private MedicalWasteImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsBagId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsBagId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022medicalWaste.proto\"8\n\rcontainsBagId\022\022\n" +
      "\ntagRequest\030\001 \001(\t\022\023\n\013tagResponse\030\002 \001(\t2C" +
      "\n\023medicalWasteService\022,\n\010GetBagId\022\016.cont" +
      "ainsBagId\032\016.containsBagId\"\000B.\n\030grpc.polu" +
      "ttionMonitoringB\020MedicalWasteImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsBagId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsBagId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsBagId_descriptor,
        new java.lang.String[] { "TagRequest", "TagResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
