// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ventilation.proto

package grpc.Ventilation;

public interface VentilationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VentilationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomId = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string roomId = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();

  /**
   * <code>string temp = 2;</code>
   */
  java.lang.String getTemp();
  /**
   * <code>string temp = 2;</code>
   */
  com.google.protobuf.ByteString
      getTempBytes();

  /**
   * <code>string date = 3;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string timeSampling = 4;</code>
   */
  java.lang.String getTimeSampling();
  /**
   * <code>string timeSampling = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimeSamplingBytes();
}
