// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ventilation.proto

package grpc.Ventilation;

public interface VentilationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VentilationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string loc = 1;</code>
   */
  java.lang.String getLoc();
  /**
   * <code>string loc = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocBytes();

  /**
   * <code>bool air = 2;</code>
   */
  boolean getAir();

  /**
   * <code>string temp = 3;</code>
   */
  java.lang.String getTemp();
  /**
   * <code>string temp = 3;</code>
   */
  com.google.protobuf.ByteString
      getTempBytes();
}
